name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to "main" if that's your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          cd php  # Navigate to the directory containing your Dockerfile
          docker build -t frustratedboy-php-apache-environment .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag frustratedboy-php-apache-environment ${{ secrets.DOCKER_USERNAME }}/frustratedboy-php-apache-environment
          docker push ${{ secrets.DOCKER_USERNAME }}/frustratedboy-php-apache-environment
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          NODE_VERSION: 14  # Specify the Node.js version here to suppress the warning
